"""empty message

Revision ID: 63f502505612
Revises: 
Create Date: 2023-11-05 17:48:04.518435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f502505612'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('daily', sa.String(), nullable=True),
    sa.Column('weekly', sa.String(), nullable=True),
    sa.Column('monthly', sa.String(), nullable=True),
    sa.Column('yearly', sa.String(), nullable=True),
    sa.Column('day1', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['goal'], ['users.id'], name=op.f('fk_goals_goal_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.Column('entry_performed_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('fk_habit_entries_habit_id_habits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habit_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_performed_date', sa.String(), nullable=True),
    sa.Column('habit_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habit_entry_id'], ['habit_entries.id'], name=op.f('fk_entry_dates_habit_entry_id_habit_entries')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_dates')
    op.drop_table('habit_entries')
    op.drop_table('goals')
    op.drop_table('users')
    op.drop_table('habits')
    # ### end Alembic commands ###
