"""empty message

Revision ID: 92cef021a825
Revises: 
Create Date: 2023-11-07 15:24:56.230996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cef021a825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('daily', sa.String(), nullable=True),
    sa.Column('weekly', sa.String(), nullable=True),
    sa.Column('monthly', sa.String(), nullable=True),
    sa.Column('yearly', sa.String(), nullable=True),
    sa.Column('day1', sa.String(), nullable=True),
    sa.Column('day2', sa.String(), nullable=True),
    sa.Column('day3', sa.String(), nullable=True),
    sa.Column('day4', sa.String(), nullable=True),
    sa.Column('day5', sa.String(), nullable=True),
    sa.Column('day6', sa.String(), nullable=True),
    sa.Column('day7', sa.String(), nullable=True),
    sa.Column('day8', sa.String(), nullable=True),
    sa.Column('day9', sa.String(), nullable=True),
    sa.Column('day10', sa.String(), nullable=True),
    sa.Column('day11', sa.String(), nullable=True),
    sa.Column('day12', sa.String(), nullable=True),
    sa.Column('day13', sa.String(), nullable=True),
    sa.Column('day14', sa.String(), nullable=True),
    sa.Column('day15', sa.String(), nullable=True),
    sa.Column('day16', sa.String(), nullable=True),
    sa.Column('day17', sa.String(), nullable=True),
    sa.Column('day18', sa.String(), nullable=True),
    sa.Column('day19', sa.String(), nullable=True),
    sa.Column('day20', sa.String(), nullable=True),
    sa.Column('day21', sa.String(), nullable=True),
    sa.Column('day22', sa.String(), nullable=True),
    sa.Column('day23', sa.String(), nullable=True),
    sa.Column('day24', sa.String(), nullable=True),
    sa.Column('day25', sa.String(), nullable=True),
    sa.Column('day26', sa.String(), nullable=True),
    sa.Column('day27', sa.String(), nullable=True),
    sa.Column('day28', sa.String(), nullable=True),
    sa.Column('day29', sa.String(), nullable=True),
    sa.Column('day30', sa.String(), nullable=True),
    sa.Column('day31', sa.String(), nullable=True),
    sa.Column('week1', sa.String(), nullable=True),
    sa.Column('week2', sa.String(), nullable=True),
    sa.Column('week3', sa.String(), nullable=True),
    sa.Column('week4', sa.String(), nullable=True),
    sa.Column('month1', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['goal'], ['users.id'], name=op.f('fk_goals_goal_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.Column('entry_performed_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('fk_habit_entries_habit_id_habits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habit_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_performed_date', sa.String(), nullable=True),
    sa.Column('habit_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habit_entry_id'], ['habit_entries.id'], name=op.f('fk_entry_dates_habit_entry_id_habit_entries')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_dates')
    op.drop_table('habit_entries')
    op.drop_table('goals')
    op.drop_table('users')
    op.drop_table('habits')
    # ### end Alembic commands ###
