"""fixing FKeys

Revision ID: c65a01056173
Revises: 92cef021a825
Create Date: 2023-11-07 16:22:24.847364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65a01056173'
down_revision = '92cef021a825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_goals_goal_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_goals_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('habit_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('day2')
        batch_op.drop_column('day6')
        batch_op.drop_column('day27')
        batch_op.drop_column('week1')
        batch_op.drop_column('day25')
        batch_op.drop_column('week2')
        batch_op.drop_column('day14')
        batch_op.drop_column('day22')
        batch_op.drop_column('day10')
        batch_op.drop_column('day28')
        batch_op.drop_column('day3')
        batch_op.drop_column('day1')
        batch_op.drop_column('day5')
        batch_op.drop_column('day12')
        batch_op.drop_column('day31')
        batch_op.drop_column('week3')
        batch_op.drop_column('day9')
        batch_op.drop_column('day11')
        batch_op.drop_column('day15')
        batch_op.drop_column('day18')
        batch_op.drop_column('day8')
        batch_op.drop_column('day24')
        batch_op.drop_column('day26')
        batch_op.drop_column('day20')
        batch_op.drop_column('day23')
        batch_op.drop_column('day17')
        batch_op.drop_column('day16')
        batch_op.drop_column('day4')
        batch_op.drop_column('day29')
        batch_op.drop_column('month1')
        batch_op.drop_column('day7')
        batch_op.drop_column('day13')
        batch_op.drop_column('day19')
        batch_op.drop_column('day21')
        batch_op.drop_column('day30')
        batch_op.drop_column('week4')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week4', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day30', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day21', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day19', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day13', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day7', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('month1', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day29', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day4', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day16', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day17', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day23', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day20', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day26', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day24', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day8', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day18', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day15', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day11', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day9', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('week3', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day31', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day12', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day5', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day1', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day3', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day28', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day10', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day22', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day14', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('week2', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day25', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('week1', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day27', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day6', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day2', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('habit_entries', schema=None) as batch_op:
        batch_op.drop_column('completed')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_goals_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_goals_goal_users', 'users', ['goal'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
